system:
    port: 8089
    remote: 'http://localhost:8189/v1/sys/update'
    defaultPath: '/data/'
    webPath: '/data/wwwroot/'
    logPath: '/data/wwwlogs/'
    dataPath: '/data/db/'
    jwtSecret: 'a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456'
