      - name: postgresql
        display_name: "postgresql"
        versions: ["15"]
        default_version: "15"
        description: "PostgreSQL关系型数据库服务器"
        author: "Community Example"
        email: "example@oneinstack.com"
        supported_os: ["ubuntu", "debian", "centos", "rhel", "rocky", "almalinux"]
        parameters:
          - name: "password"
            type: "string"
            required: true
            description: "管理员密码"
          - name: "port"
            type: "integer"
            default: 5432
            description: "服务端口"
          - name: "data_dir"
            type: "string"
            default: "/var/lib/postgresql"
            description: "数据目录"
        tags: ["database", "postgresql"]
        category: "database"
        difficulty: "medium"
        estimated_time: "5-10分钟"
