package ssh

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"time"

	"oneinstack/app"
	"oneinstack/internal/services/audit"
)

var ErrTerminalUnavailable = errors.New("terminal runtime unavailable")

const (
	rootTerminalUser             = "root"
	rootTerminalWorkingDirectory = "/root"
	rootTerminalBashRC           = `# Generated by Oneinstack Panel for the managed Root Web terminal.
if [ -r /etc/bash.bashrc ]; then
  . /etc/bash.bashrc
fi
if [ -r /root/.bashrc ]; then
  . /root/.bashrc
fi

export TERM=xterm-256color
export CLICOLOR=1
if command -v dircolors >/dev/null 2>&1; then
  eval "$(dircolors -b 2>/dev/null)"
fi

alias ls='command ls --color=always --classify --format=vertical --tabsize=8'
alias ll='command ls -alFh --color=always'
alias la='command ls -AF --color=always --format=vertical --tabsize=8'
alias grep='command grep --color=auto'
shopt -s checkwinsize

PS1='\[\e[38;5;45m\]\u@\h\[\e[0m\]:\[\e[38;5;75m\]\w\[\e[0m\] \[\e[38;5;214m\]\$\[\e[0m\] '
_one_terminal_prompt_sync() {
  printf '\033]0;%s@%s:%q\007' "$USER" "${HOSTNAME%%.*}" "$PWD"
}
PROMPT_COMMAND=_one_terminal_prompt_sync
`
)

type TerminalPolicy struct {
	Enabled       bool          `json:"enabled"`
	MaxDuration   time.Duration `json:"-"`
	IdleTimeout   time.Duration `json:"-"`
	MaxConcurrent int           `json:"maxConcurrent"`
	MaxPerUser    int           `json:"maxPerUser"`
}

type TerminalSecurityStatus struct {
	Enabled   bool `json:"enabled"`
	Available bool `json:"available"`
	// IsolationAvailable is retained for compatibility with older WebUI builds.
	IsolationAvailable bool   `json:"isolationAvailable"`
	Reason             string `json:"reason,omitempty"`
	RuntimeUser        string `json:"runtimeUser"`
	WorkingDirectory   string `json:"workingDirectory"`
	MaxSessionMinutes  int    `json:"maxSessionMinutes"`
	IdleMinutes        int    `json:"idleMinutes"`
	MaxOutputMB        int    `json:"maxOutputMB"`
	MaxConcurrent      int    `json:"maxConcurrent"`
	MaxPerUser         int    `json:"maxPerUser"`
	ActiveSessions     int    `json:"activeSessions"`
	CommandAudit       bool   `json:"commandAudit"`
	NoNewPrivileges    bool   `json:"noNewPrivileges"`
	Capabilities       string `json:"capabilities"`
	PrivilegeMode      string `json:"privilegeMode"`
}

func CurrentTerminalPolicy() TerminalPolicy {
	system := app.ONE_CONFIG.System
	return TerminalPolicy{
		Enabled:       system.TerminalEnabled,
		MaxDuration:   time.Duration(system.TerminalSessionMins) * time.Minute,
		IdleTimeout:   time.Duration(system.TerminalIdleMins) * time.Minute,
		MaxConcurrent: system.TerminalMaxConcurrent,
		MaxPerUser:    system.TerminalMaxPerUser,
	}
}

func GetTerminalSecurityStatus() TerminalSecurityStatus {
	policy := CurrentTerminalPolicy()
	status := TerminalSecurityStatus{
		Enabled:           policy.Enabled,
		RuntimeUser:       rootTerminalUser,
		WorkingDirectory:  rootTerminalWorkingDirectory,
		MaxSessionMinutes: int(policy.MaxDuration / time.Minute),
		IdleMinutes:       int(policy.IdleTimeout / time.Minute),
		MaxOutputMB:       terminalMaxOutputBytes >> 20,
		MaxConcurrent:     policy.MaxConcurrent,
		MaxPerUser:        policy.MaxPerUser,
		ActiveSessions:    DefaultSessions.ActiveCount(),
		CommandAudit:      audit.Default() != nil,
		NoNewPrivileges:   false,
		Capabilities:      "full",
		PrivilegeMode:     "root",
	}
	_, _, err := validateRootTerminalRuntime(policy)
	if err != nil {
		status.Reason = err.Error()
		return status
	}
	if !status.CommandAudit {
		status.Reason = "终端审计链不可用"
		return status
	}
	status.Available = true
	status.IsolationAvailable = true
	return status
}

func terminalCommand(
	ctx context.Context,
	policy TerminalPolicy,
) (*exec.Cmd, func(), error) {
	prlimit, bash, err := validateRootTerminalRuntime(policy)
	if err != nil {
		return nil, nil, err
	}
	rcPath, cleanup, err := createRootTerminalBashRC()
	if err != nil {
		return nil, nil, fmt.Errorf("%w: 创建终端初始化文件失败: %v", ErrTerminalUnavailable, err)
	}
	return buildRootTerminalCommand(ctx, policy, prlimit, bash, rcPath), cleanup, nil
}

func validateRootTerminalRuntime(policy TerminalPolicy) (string, string, error) {
	if !policy.Enabled {
		return "", "", fmt.Errorf("%w: Web 终端未启用", ErrTerminalUnavailable)
	}
	if os.Geteuid() != 0 {
		return "", "", fmt.Errorf(
			"%w: Panel 必须由 root 启动，才能创建 root 终端",
			ErrTerminalUnavailable,
		)
	}
	rootDirectory, err := os.Stat(rootTerminalWorkingDirectory)
	if err != nil || !rootDirectory.IsDir() {
		return "", "", fmt.Errorf("%w: /root 工作目录不可用", ErrTerminalUnavailable)
	}
	prlimit, err := resolveTerminalExecutable(
		"prlimit",
		"/usr/bin/prlimit",
		"/bin/prlimit",
	)
	if err != nil {
		return "", "", fmt.Errorf("%w: 缺少 prlimit", ErrTerminalUnavailable)
	}
	bash, err := resolveTerminalExecutable(
		"bash",
		"/bin/bash",
		"/usr/bin/bash",
	)
	if err != nil {
		return "", "", fmt.Errorf("%w: /bin/bash 不可用", ErrTerminalUnavailable)
	}
	return prlimit, bash, nil
}

func createRootTerminalBashRC() (string, func(), error) {
	file, err := os.CreateTemp("", "one-terminal-*.bashrc")
	if err != nil {
		return "", nil, err
	}
	path := file.Name()
	cleanup := func() {
		_ = os.Remove(path)
	}
	if _, err = file.WriteString(rootTerminalBashRC); err != nil {
		_ = file.Close()
		cleanup()
		return "", nil, err
	}
	if err = file.Close(); err != nil {
		cleanup()
		return "", nil, err
	}
	return path, cleanup, nil
}

func buildRootTerminalCommand(
	ctx context.Context,
	policy TerminalPolicy,
	prlimit string,
	bash string,
	rcPath string,
) *exec.Cmd {
	cpuSeconds := int(policy.MaxDuration.Seconds())
	if cpuSeconds < 60 {
		cpuSeconds = 60
	}
	command := exec.CommandContext(
		ctx,
		prlimit,
		"--core=0",
		"--nproc=128",
		"--nofile=256",
		"--fsize=536870912",
		"--as=2147483648",
		"--cpu="+strconv.Itoa(cpuSeconds),
		"--",
		bash,
		"--noprofile",
		"--rcfile",
		rcPath,
		"-i",
	)
	command.Dir = rootTerminalWorkingDirectory
	command.Env = []string{
		"TERM=xterm-256color",
		"CLICOLOR=1",
		"LANG=C.UTF-8",
		"LC_ALL=C.UTF-8",
		"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
		"HOME=/root",
		"USER=root",
		"LOGNAME=root",
		"SHELL=" + bash,
		"TMOUT=" + strconv.Itoa(int(policy.IdleTimeout.Seconds())),
	}
	return command
}

func resolveTerminalExecutable(name string, candidates ...string) (string, error) {
	for _, candidate := range candidates {
		info, err := os.Stat(candidate)
		if err == nil && info.Mode().IsRegular() && info.Mode().Perm()&0111 != 0 {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("%s executable not found in trusted locations", name)
}
