package webui

import (
	"archive/zip"
	"bytes"
	_ "embed"
	"fmt"
	"io/fs"
	"strings"
	"sync"
)

// archive contains the production frontend generated by Oneinstack-Panel-Web.
//
//go:embed app.zip
var archive []byte

var embedded struct {
	sync.Once
	fileSystem fs.FS
	err        error
}

func FS() (fs.FS, error) {
	embedded.Do(func() {
		reader, err := zip.NewReader(bytes.NewReader(archive), int64(len(archive)))
		if err != nil {
			embedded.err = fmt.Errorf("open embedded web archive: %w", err)
			return
		}
		embedded.fileSystem = reader
	})
	return embedded.fileSystem, embedded.err
}

func ReadFile(name string) ([]byte, error) {
	name = strings.TrimPrefix(name, "/")
	if !fs.ValidPath(name) {
		return nil, fs.ErrInvalid
	}
	fileSystem, err := FS()
	if err != nil {
		return nil, err
	}
	return fs.ReadFile(fileSystem, name)
}
